use_frameworks!

platform :ios, '8.0'

target 'RegisterTemplateIOS13_Example' do
  pod 'RegisterTemplateIOS13', :path => '../'

  target 'RegisterTemplateIOS13_Tests' do
    inherit! :search_paths

    
  end
end
